[package]
name = "patchwork_evaluator"
version = "1.0.0"
authors = ["Nico Zeitz", "Fabian Wolf"]
edition = "2021"

[dependencies]
game = { path = "../game" }
patchwork_core = { path = "../patchwork_core" }
