[package]
name = "max-button-income"
description = "Analysis of the max button income in patchwork"
edition = "2021"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
itertools = "0.12.0"
rayon = "1.8.1"
