[package]
name = "upi"
description = "Package containing the Universal Patchwork Interface (UPI) protocol"
edition = "2021"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.79"
