[package]
name = "console"
version = "1.0.0"
authors = ["Nico Zeitz", "Fabian Wolf"]
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
patchwork = { path = "../patchwork" }
regex = "1.10.2"
