[package]
name = "evaluator-train"
description = "Trains evaluators for game positions in patchwork"
edition = "2021"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
mkl = ["candle-core/mkl", "candle-nn/mkl", "evaluator/mkl"]
accelerate = [
    "candle-core/accelerate",
    "candle-nn/accelerate",
    "evaluator/accelerate",
]
cuda = [
    "candle-core/cuda",
    "candle-core/cudnn",
    "candle-nn/cuda",
    "evaluator/cuda",
]
metal = ["candle-core/metal", "candle-nn/metal", "evaluator/metal"]


[dependencies]
regex = { version = "1.10.3" }
candle-core = { version = "0.4.1", git = "https://github.com//huggingface/candle.git" }
candle-nn = { version = "0.4.1", git = "https://github.com//huggingface/candle.git" }
greedy-player = { path = "../../greedy-player" }
patchwork-core = { path = "../../patchwork-core" }
evaluator = { path = "../../evaluator" }
boxcar = "0.2.4"
tqdm = "0.6.0"
rand = "0.8.5"
rand_distr = "0.4.3"
