[package]
name = "patchwork_minimax_player"
version = "1.0.0"
authors = ["Nico Zeitz", "Fabian Wolf"]
edition = "2021"

[dependencies]
game = { path = "../game" }
patchwork_core = { path = "../patchwork_core" }
patchwork_evaluator = { path = "../patchwork_evaluator" }
rand = "0.8.5"
