# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# cargo clippy --fix --allow-dirty
# cargo watch

[workspace]
members = [
    "patchwork",
    "patchwork_core",
    "patchwork_macros",
    "patchwork_player",
    "console",
]
resolver = "2"

[workspace.lints.rust]
missing_debug_implementations = "warn"
rust_2018_idioms = "warn"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
