# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# cargo clippy --fix --allow-dirty
# cargo watch

[workspace]
members = [
    "console",
    "game",
    "patchwork",
    "patchwork_core",
    "patchwork_macros",
    "patchwork_evaluator",
    "patchwork_human_player",
    "patchwork_random_player",
    "patchwork_greedy_player",
    "patchwork_mcts_player",
    "patchwork_minimax_player",
    "patchwork_negamax_player",
    "patchwork_alphazero_player",
    "tree_policy",
]
resolver = "2"

[lints.rust]
missing_debug_implementations = "warn"
rust_2018_idioms = "warn"
missing_docs = "warn"

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
