name: Build Studienarbeit LaTeX document
on:
    push:
        branches:
            - main
        paths:
            - T3_3101/**

jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v3
            - name: Compile Studienarbeit LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                  working_directory: ./T3_3101
                  root_file: Praxisbericht.tex
            - name: Upload PDF file
              uses: actions/upload-artifact@v3
              with:
                  name: PDF
                  path: ./T3_3101/Praxisbericht.pdf
            - name: Release Studienarbeit LaTeX document
              uses: softprops/action-gh-release@v1
              with:
                  files: ./T3_3101/Praxisbericht.pdf
