[package]
name = "patchwork_mcts_player"
version = "1.0.0"
authors = ["Nico Zeitz", "Fabian Wolf"]
edition = "2021"

[dependencies]
patchwork_core = { path = "../patchwork_core" }
tree_policy = { path = "../tree_policy" }
patchwork_evaluator = { path = "../patchwork_evaluator" }
rand = "0.8.5"
