[package]
name = "patchwork_core"
version = "0.1.0"
edition = "2021"

[dependencies]
derivative = "2.2.0"
lazy_static = "1.4.0"
patchwork_macros = { path = "../patchwork_macros" }
rand = "0.8.5"
rand_xoshiro = "0.6.0"
rayon = "1.8.0"
