[package]
name = "patchwork"
version = "1.0.0"
authors = ["Nico Zeitz", "Fabian Wolf"]
edition = "2021"

[dependencies]
patchwork_action_sorter = { path = "../patchwork_action_sorter" }
patchwork_core = { path = "../patchwork_core" }
patchwork_evaluator = { path = "../patchwork_evaluator" }
patchwork_macros = { path = "../patchwork_macros" }
patchwork_alphazero_player = { path = "../patchwork_alphazero_player" }
patchwork_human_player = { path = "../patchwork_human_player" }
patchwork_random_player = { path = "../patchwork_random_player" }
patchwork_greedy_player = { path = "../patchwork_greedy_player" }
patchwork_mcts_player = { path = "../patchwork_mcts_player" }
patchwork_minimax_player = { path = "../patchwork_minimax_player" }
patchwork_principal_variation_search_player = { path = "../patchwork_principal_variation_search_player" }
