[package]
name = "patchwork_random_player"
version = "1.0.0"
authors = ["Nico Zeitz", "Fabian Wolf"]
edition = "2021"

[dependencies]
patchwork_core = { path = "../patchwork_core" }
rand = "0.8.5"
rand_xoshiro = "0.6.0"
