# to use this workflow, you need to tag a commit
# https://git-scm.com/book/en/v2/Git-Basics-Tagging
# git add .
# git commit -m "message"
# git tag -a 1.0.0 -m "message"
# git push origin main 1.0.0

name: Build Studienarbeit LaTeX document
on:
    push:
        branches:
            - main
        paths:
            # run when something in ./T3_3101/ folder changes
            - 'T3_3101/**'
            - '**/*.tex'
        tags:
            - '*'

permissions:
    contents: write

jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v3
            - name: Compile Studienarbeit LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                  working_directory: ./T3_3101
                  root_file: Praxisbericht.tex
            # - name: Upload PDF file
            #   uses: actions/upload-artifact@v3
            #   with:
            #       name: PDF
            #       path: ./T3_3101/Praxisbericht.pdf
            - name: Release Studienarbeit LaTeX document
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  token: ${{ github.token }}
                  name: Release Version ${{ github.ref_name }} of Studienarbeit LaTeX document
                  files: ./T3_3101/Praxisbericht.pdf
