name: Rust Continuous integration
on:
    push:
        branches:
            - main
        paths:
            - code/patchwork/**
    # pull_request:
    #     branches:
    #         - main
    #     paths:
    #         - code/patchwork/**

jobs:
    check:
        name: cargo check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Cargo Check
              working-directory: ./code/patchwork
              run: cargo check --all-targets
    test:
        name: cargo test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Cargo Test
              working-directory: ./code/patchwork
              run: cargo test --workspace --all-targets
            - name: Cargo Doc Test
              working-directory: ./code/patchwork
              run: cargo test --workspace --doc
            - name: Cargo Bench
              working-directory: ./code/patchwork/patchwork-core
              run: cargo bench --bench performance
    fmt:
        name: cargo fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Cargo Fmt
              working-directory: ./code/patchwork
              run: cargo fmt --all -- --check
    clippy:
        name: cargo clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Cargo Clippy
              working-directory: ./code/patchwork
              run: cargo clippy --all -- -D warnings
